[package]
name = "weighted_schedule"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-task = "4"
flume = "0.11.0"
futures = "0.3"
crossbeam = "0.8"
once_cell = "1"
